// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:serial_app/entities/estado_del_sistema/estado_del_sistema_model.dart'
    as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'BoxGateDataModel',
            r'.BoxGateDataModel',
            134217735,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 3, 4, 5, 6, 7, 8, 15, 16, 17],
            const <int>[8, 6, 18, 15, 19, 7, 9, 10, 11, 12, 13, 14],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (cerradura, puerta, ultimaApertura, duracion,
                      codigoCierre, estado) =>
                  b
                      ? prefix1.BoxGateDataModel(cerradura, puerta,
                          ultimaApertura, duracion, codigoCierre, estado)
                      : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.BoxGateDataModel.fromJson(json) : null
            },
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'cerradura',
            67240965,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.JsonProperty(name: 'cerradura')]),
        r.VariableMirrorImpl(
            r'puerta',
            67240965,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.JsonProperty(name: 'puerta')]),
        r.VariableMirrorImpl(
            r'ultimaApertura',
            67240965,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.JsonProperty(name: 'ultimaApertura')]),
        r.VariableMirrorImpl(
            r'duracion',
            67240965,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.JsonProperty(name: 'duracion')]),
        r.VariableMirrorImpl(
            r'codigoCierre',
            67240965,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.JsonProperty(name: 'codigoCierre')]),
        r.VariableMirrorImpl(
            r'estado',
            67240965,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.JsonProperty(name: 'estado')]),
        r.MethodMirrorImpl(
            r'toString',
            2097154,
            0,
            -1,
            2,
            2,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'toJson',
            35651586,
            0,
            -1,
            3,
            4,
            null,
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'==',
            2097154,
            0,
            -1,
            5,
            5,
            const <int>[],
            const <int>[0],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 9),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 10),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 11),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 3, 12),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 4, 13),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 5, 14),
        r.MethodMirrorImpl(
            r'hashCode',
            2097155,
            0,
            -1,
            6,
            6,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'',
            128,
            0,
            -1,
            0,
            0,
            const <int>[],
            const <int>[1, 2, 3, 4, 5, 6],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(
            r'fromJson',
            1,
            0,
            -1,
            0,
            0,
            const <int>[],
            const <int>[7],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[8],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            8,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'cerradura',
            67240966,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'puerta',
            67240966,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'ultimaApertura',
            67240966,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'duracion',
            67240966,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'codigoCierre',
            67240966,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'estado',
            67240966,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'json',
            67141638,
            17,
            const prefix0.JsonSerializable(),
            -1,
            -1,
            -1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            18,
            const prefix0.JsonSerializable(),
            -1,
            9,
            9,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.BoxGateDataModel,
        String,
        String,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        bool,
        int,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'cerradura': (dynamic instance) => instance.cerradura,
        r'puerta': (dynamic instance) => instance.puerta,
        r'ultimaApertura': (dynamic instance) => instance.ultimaApertura,
        r'duracion': (dynamic instance) => instance.duracion,
        r'codigoCierre': (dynamic instance) => instance.codigoCierre,
        r'estado': (dynamic instance) => instance.estado
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
